### PR TITLE
Homepage no longer shows map on login

### PR DESCRIPTION
**Pull request by JosephBargallo**
When logging in the user no longer is greeted with a display of the map, instead setting the lower panel to full screen. User can bring the map back up by clicking on the Map button when browsing the facililites tab.

### CODE REVIEW

**Comment by JosephBargallo** [comment]
Formatting for the homepage is required since it is being cut off slightly when viewing the facilities tab.

**Review by daviddelgadol — CHANGES_REQUESTED** [review]
On the initial Main view, the map does disappear, but if one goes to the facilities map and then goes back to the main menu, the map remains open.

**Comment by JosephBargallo** [comment]
Changes have been made, map now can be toggled on and off. Facilities tab is no longer getting cut off.

**Review by RoniRaad — APPROVED** [review]

**Review by daviddelgadol — APPROVED** [review]

**Comment by RoniRaad** [comment]
Forgot to comment earlier but this change looked good and worked locally when tested.

**Pull request merged**
