### PR TITLE
All images for clinics

### PR DESCRIPTION
**Pull request by jgonz11**
This file contain all images for clinics

### CODE REVIEW

**Comment by edumorlom** [comment]
how does the app know which image is which.

**Comment by edumorlom** [comment]
Any update? @jgonz11

**Comment by jgonz11** [comment]
We have been working on that. We might need a one to one meeting

**Comment by edumorlom** [comment]
Ok feel free to ping me :)

**Comment by edumorlom** [comment]
please reopen when ready.

**Pull request closed without merging**
