### PR TITLE
Sign up date of birth no longer allows future dates.

### PR DESCRIPTION
**Pull request by JosephBargallo**
When entering their date of birth on sign up, the user will no longer be allowed to enter a date set in the future.

### CODE REVIEW

**Review by daviddelgadol — APPROVED** [review]
Simple yet useful fix, great job.

**Review by probycode — COMMENTED** [review]
works good

**Review by probycode — APPROVED** [review]
looks good

**Review by Sunnex — APPROVED** [review]
Well done implementing an easy fix to the problem using an else if statement to check if its past the current date alerting the user if its invalid having them to re-enter a valid date. When testing your code I tried **3 test cases:** one year after, one month after, and one day after. As a result, it passed all cases giving me the alert to re-enter today's date, which gave me access to the next step.

**Pull request merged**
