### PR TITLE
#132 Swipe up css on login

### PR DESCRIPTION
**Pull request by LeonelADiaz**
#132 Fixed issues. 

This issue only affected Android devices, as iOS didn't encounter it. Solution was to remove TouchableHighlight as it prevented GestureRecognizer from being functional in Android if the SwipeUp component was moved into a View. The CSS element kept coming up unless it was in a View, so that's why it was placed in it. 

Also had to change the bottom property so that it was formatted correctly. 

Let me know if there's any concerns.

### CODE REVIEW

**Comment by edumorlom** [comment]
This looks good but TouchableHighlight was used to dismiss the keyboard.
How can the user dismiss the keyboard now?

**Comment by LeonelADiaz** [comment]
> 
> 
> This looks good but TouchableHighlight was used to dismiss the keyboard.
> How can the user dismiss the keyboard now?

When would it dismiss the keyboard? Currently on press the return key after typing in your email or password, the keyboard dismisses, and when you click Sign-In, it also dismisses. That's why I was confused on what exactly Toucheable Highlight does as the keyboard still dismisses in those cases without it on both OS.

**Comment by edumorlom** [comment]
If you tap on the background, it will dismiss the keyboard that's what most people do which is why I added the Touch Highlight. There is no other way?

**Comment by LeonelADiaz** [comment]
> 
> 
> If you tap on the background, it will dismiss the keyboard that's what most people do which is why I added the Touch Highlight. There is no other way?

I didn't realize that was an option. I'm going to test it a bit more today and let you know what I find.

**Comment by LeonelADiaz** [comment]
@edumorlom Runs and works as intended. Was able to keep ToucheableHighlight. Changed the property bottom and removed "position: absolute" from SwipeUp as it affected display of button.
Screenshot_20201012-194355_Expo
Screenshot_20201012-194429_Expo

**Comment by edumorlom** [comment]
Amazing! Thank you.

**Pull request merged**
