### PR TITLE
Fixed Map to always appear

### PR DESCRIPTION
**Pull request by JoseBaez010**
Map will always appear now throughout the app.

### CODE REVIEW

**Comment by JoseBaez010** [comment]
IMG_3454
IMG_3455
m/edumorlom/nuMom/assets/83191691/189eae4b-8e06-4403-9201-13460dd8c25d)

**Review by jocelyndr — APPROVED** [review]
The app runs well and shows the map

**Review by vroja035 — APPROVED** [review]
Everything looks good. Map is always showing now.

**Review by vroja035 — APPROVED** [review]
Everything looks good. Map is always showing now.

**Pull request merged**
