### PR TITLE
added contrast to text boxes.

### PR DESCRIPTION
**Pull request by RoniRaad**

### CODE REVIEW

**Review by daviddelgadol — APPROVED** [review]
Really good change to add contrast to text boxes. Next time just make sure to not commit the .gitignore file.

**Review by JosephBargallo — APPROVED** [review]

**Comment by edumorlom** [comment]
@RoniRaad can u get rid of unnecessary commits? such as what David pointed out.

**Review by JosephBargallo — COMMENTED** [review]
No issues when running, I was able to see the contrast that was added.

**Comment by RoniRaad** [comment]
@edumorlom The gitignore is suppose to be there, it ignores the files that visual studio creates and is a non code change.

**Pull request merged**
