### PR TITLE
Fixed UI issue#691

### PR DESCRIPTION
**Pull request by jocelyndr**
Fixed the padding and margin for the Menu component
IMG_1840

### CODE REVIEW

**Comment by edumorlom** [comment]
can we make visit site button the dame width as the other?

**Comment by edumorlom** [comment]
@jocelyndr

**Comment by jocelyndr** [comment]
Done
IMG_1861

**Review by JoseBaez010 — APPROVED** [review]
Everything looks good and the change was made.

**Review by vroja035 — APPROVED** [review]
Everything looks good.

**Pull request merged**
