### PR TITLE
Additional dropdown for shots in immunizations (Fix for Issue #353)

### PR DESCRIPTION
**Pull request by lroche823**
<<>> Removed from Selecting Immunization message and extra drop down added for shots. Fix for #353

### CODE REVIEW

**Review by julianlopez6850 — CHANGES_REQUESTED** [review]
Hey,

This looks good, but I found 2 small issues that you might be able to fix quickly.

- [ ] The first issue is that only the vaccination type field needs to be filled out to save the immunization if you never select a dosage #. (if you change the dose #, and then change back to 'Select Dosage', you can't save [correct], but if you don't ever select a dosage # in the first place, you can save [shouldn't be the case]). 

**Fix:** Add an OR `!dosage` condition in the if statement on line 71

- [ ] The second (I believe I found a fix) is that the dropdowns put the selection in the center of the dropdown  when you click on them again, so this causes the vaccination type dropdown to go mostly off-screen above the top of the page.

**Fix:** Comment out line 713 `transform: [{ translateY }],` in node_modules > react-native-material-dropdown-v2 > src\components > dropdown> index.js

It is probably easiest to get here if you
`cd node_modules/react-native-material-dropdown-v2/src/components/dropdown`
`code index.js`
on your terminal

(found this fix here: https://github.com/n4kz/react-native-material-dropdown/issues/206 on the original repository that has not been maintained since its release it seems)

**Review by Supercala155 — CHANGES_REQUESTED** [review]
The second drop down with the doses currently does not serve any purpose, as in it doesn't show this information anywhere after it has been selected. When one of the immunization records has been saved, it should show the dosage along side the type of shot it is.

**Comment by lroche823** [comment]
@julianlopez6850 So, I was able to fix both issues locally without a problem, but the second one is a little more complicated because it involves editing a dependency. node_modules files are not pushed onto git along with the rest of the code so there are two ways to go about this from my research:
[FIX 1](https://whatapalaver.co.uk/npm-dependency) involves creating a fork from the original repo and replacing the folder in node_modules with my own fork (seems like the easier fix at first glance?)
[FIX 2](https://www.npmjs.com/package/patch-package) involves downloading a new dependency that makes it so that the edits on node_modules are saved onto github.
I'll go through with whatever seems like a more foolproof fix, but first I wanted feedback from the reviewers abt what seems like the best course of action

**Review by julianlopez6850 — APPROVED** [review]
All changes have been made except for the issue with changing a node_modules file. We can merge this pull request into development, and create a new issue for the node_modules file to get the ball rolling with this pull request.

**Pull request merged**
